version: '3.9'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    env_file: .env.production
    depends_on:
      - "database"
    command: ["./wait-for-it.sh", "database:5432", "--", "npm", "start"]
  database:
    image: postgres:13
    env_file: .env.production
     